version: 2
jobs:
  build:
    machine:
      - docker_layer_caching: true

    working_directory: ~/rails5
    steps:
      - checkout
      - run:
        name: Test Command
        command: |
            ls -las
      - run:
        name: Build Project
        command: |
            docker-compose build