#version: 2
#jobs:
#  build:
#    docker:
#      - image: circleci/buildpack-deps:stretch-curl
#    working_directory: ~/rails5
#    steps:
#      - setup_remote_docker:
#          version: 18.09.3
#          docker_layer_caching: true
#      - checkout
#      - run:
#          name: Test Command
#          command: |
#            ls -las
#      - run:
#          name: Build Project
#          command: |
#            docker-compose build
#      - run:
#          name: Verify Docker images
#          command: |
#            docker images
#      - run:
#          name: Run Docker containers
#          command: |
#            set -x
#            docker-compose up -d
#            docker run --network container:app \
#              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000
#      - run:
#          name: Wait for containers
#          command: |
#            dockerize -wait tcp://localhost:3306 -timeout 30s
#      - run:
#          name: Setup Databases
#          command: |
#            docker-compose exec app rake db:create db:migrate
#            docker-compose run app rake db:create db:create

## Example for machine executor

version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    working_directory: ~/rails5

    steps:
      - checkout
      - run:
          name: Test Command
          command: |
            ls -las
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Build Project
          command: |
            docker-compose build
      - run:
          name: Verify Docker images
          command: |
            docker images
      - run:
          name: Run Docker containers
          command: |
            set -x
            docker-compose up -d
      - run:
          name: Wait for containers
          command: |
            dockerize -wait tcp://localhost:3306 -timeout 30s
            dockerize -wait tcp://localhost:3000 -timeout 30s
      - run:
          name: List running containers
          command: |
            docker container ls
      - run:
          name: Setup Databases
          command: |
            docker-compose run app rake db:create
            docker-compose exec app rake db:migrate