version: 2
jobs:
  build:
    machine: true
    working_directory: ~/rails5
    steps:
      - checkout
      - run:
        name: Test Command
        command: |
          ls -las
      - run:
        name: Build Project
        command: |
          docker-compose build