version: 2
jobs:
  build:
    machine:
      - docker_layer_caching: true

    working_directory: ~/rails5
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Now we will build the project'
      - run:
        name: Build Project
          command: |
            docker-compose build